spring:
  application:
    name: laptop-store

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


jwt:
  secret: 2de2d4409d1eb38bb57c092d5734ecdde510d5bacb0033023a4a83fae17c797c
  access-token-expires-in-ms: 900000   #900000
  refresh-token-expires-in-ms: 604800000 #604800000

logging:
  level:
    org.springframework.security: TRACE